// Mirror of data.js — minimal fields for middleware + OG image generation.
// Slugs are pre-computed: name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '')
// Sync manually when data.js changes.

const FESTIVALS_META = [
  // MAY
  {
    name: "Space to Emerge",
    slug: "space-to-emerge",
    start: "2026-05-01",
    end: "2026-05-04",
    location: "Lake District",
    country: "England",
    description: "Weekend retreat in the Lake District with healing therapies, workshops and dancing with like-minded people in a bluebell wood overlooking Lake Windermere.",
    img: "/img/2018_01_download.jpg",
    tags: ["Mindfulness"],
  },
  {
    name: "The Cocoon",
    slug: "the-cocoon",
    start: "2026-05-03",
    end: "2026-05-10",
    location: "Crete",
    country: "Greece",
    description: "7-day retreat in Crete for conscious intimacy, sensitivity and deep transformation. Workshops, rituals and ocean immersion for authentic relating.",
    img: "/img/2025_08_intimacyfestivalcrete.jpg",
    tags: ["Mindfulness"],
  },
  {
    name: "Elfia Vorden Festival",
    slug: "elfia-vorden-festival",
    start: "2026-05-08",
    end: "2026-05-10",
    location: "Vorden",
    country: "Netherlands",
    description: "Fantasy festival at Castle Vorden in the Netherlands. Over 30,000 dreamers, 200+ acts and three full days of elves, costumes and magic.",
    img: "/img/2024_04_278638909_5270052903028574_757411625807642330_n.jpg",
    tags: ["Arts"],
  },
  {
    name: "Contact in Paradise",
    slug: "contact-in-paradise",
    start: "2026-05-11",
    end: "2026-05-17",
    location: "Wien",
    country: "Austria",
    description: "Contact improvisation festival in Vienna. Community of creative dancers with world-class musicians and instructors in a transformative playground.",
    img: "/img/2023_04_contact-improvisation.jpg",
    tags: ["Mindfulness"],
  },
  {
    name: "Wood Festival",
    slug: "wood-festival",
    start: "2026-05-15",
    end: "2026-05-17",
    location: "Braziers Park, Oxfordshire",
    country: "UK",
    description: "Small, welcoming festival in Oxfordshire with music, workshops, food and drink. Sustainable, family-friendly and award-winning green event.",
    img: "/img/2019_09_ifXSvNbdqlR1Xq0u7Yh5y1Y-rCM.png",
    tags: ["World Music"],
  },
  {
    name: "Burning Nest",
    slug: "burning-nest",
    start: "2026-05-18",
    end: "2026-05-24",
    location: "Exeter",
    country: "England",
    description: "UK Burning Man-inspired gathering in Exeter celebrating creativity, radical self-expression and community. Memberships not tickets — everyone participates.",
    img: "/img/2016_02_10562929_342239425977104_2531060990450608070_n.png",
    tags: ["Burner", "Arts"],
  },
  {
    name: "HowTheLightGetsIn",
    slug: "howthelightgetsin",
    start: "2026-05-22",
    end: "2026-05-25",
    location: "Hay-on-Wye",
    country: "Wales",
    description: "Festival of ideas and music at the edge of the Black Mountains in Wales. World-class thinkers by day, dancing late into the night in the famous book town.",
    img: "/img/2022_01_HowTheLightGetsIn-Wales.jpg",
    tags: ["Arts"],
  },
  {
    name: "Roma Tribal Meeting",
    slug: "roma-tribal-meeting",
    start: "2026-05-22",
    end: "2026-05-24",
    location: "Rome",
    country: "Italy",
    description: "3-day tribal belly dance festival in Rome. Workshops, exhibitions and performances celebrating FatChanceBellyDance and Fusion Belly Dance styles.",
    img: "/img/2019_04_Bildschirmfoto-2026-01-20-um-14.01.26.png",
    tags: ["Arts", "World Music"],
  },
  {
    name: "Flamingalo",
    slug: "flamingalo",
    start: "2026-05-27",
    end: "2026-05-31",
    location: "Alentejo",
    country: "Portugal",
    description: "Burning Man-inspired festival in Alentejo, Portugal. A gathering of creative Europeans 90 minutes from Lisbon, guided by the 10 principles of Burning Man.",
    img: "/img/2026_03_flamingalo-burn-portugal-scaled.jpg",
    tags: ["Burner", "Arts"],
  },
  {
    name: "Conscious Camp",
    slug: "conscious-camp",
    start: "2026-05-28",
    end: "2026-05-31",
    location: "Shrewsbury",
    country: "UK",
    description: "Intimate 200-person gathering in Wales for music, workshops and community. Alcohol-free space for authentic connection and inner work.",
    img: "/img/2023_04_circle3-960x400-1.jpg",
    tags: ["Offgrid"],
  },
  {
    name: "Earth Garden",
    slug: "earth-garden",
    start: "2026-05-29",
    end: "2026-05-31",
    location: "Ta' Qali",
    country: "Malta",
    description: "Long weekend festival in Malta blending world music, electronic beats, healing and cultural diversity. 5 stages, 120+ acts from around the world.",
    img: "/img/2019_03_Bildschirmfoto-2026-01-20-um-14.08.31-1024x976.png",
    tags: ["World Music"],
  },
  {
    name: "Psychedelic Experience Festival",
    slug: "psychedelic-experience-festival",
    start: "2026-05-29",
    end: "2026-06-01",
    location: "Rüthen",
    country: "Germany",
    description: "Open-air psytrance festival near Rüthen, Germany. 55 hours of non-stop music across two floors, art market, fire installations, and 2033 lakes.",
    img: "/img/2017_05_PsychedelicExperience-00041.jpg",
    tags: ["Psytrance", "Electronic"],
  },
  {
    name: "Space of Love Festival",
    slug: "space-of-love-festival",
    start: "2026-05-29",
    end: "2026-06-07",
    location: "Öland",
    country: "Sweden",
    description: "Festival on the Swedish isle of Öland with workshops from family constellation to yoga and African dance. A chance to slow down and open your heart.",
    img: "/img/2016_03_spaceoflove.jpg",
    tags: ["Mindfulness", "Offgrid"],
  },
  {
    name: "Klub Dramatik",
    slug: "klub-dramatik",
    start: "2026-05-23",
    end: "2026-05-24",
    location: "Antwerp",
    country: "Belgium",
    description: "Open-air electronic music festival in Antwerp's Nachtegalenpark forest with curated funk, disco, house and techno across three intimate stages.",
    img: "https://ticketswap-image-cdn.b-cdn.net/public/202605/klub-dramatik-festival-2026-nachtegalenpark-20-may-2026-1779109430.image.jpeg",
    tags: ["Electronic", "Techno"],
  },
  {
    name: "Lentekabinet",
    slug: "lentekabinet",
    start: "2026-05-23",
    end: "2026-05-24",
    location: "Netherlands",
    country: "Netherlands",
    description: "Two-day spring edition of Het Kabinet festival in the Netherlands. Underground electronic music across intimate stages as the season warms up.",
    img: "/img/lentakabinet-2026.webp",
    tags: ["Electronic", "Techno"],
  },
  {
    name: "Refractor Festival",
    slug: "refractor-festival",
    start: "2026-05-29",
    end: "2026-05-31",
    location: "Valdeverdeja",
    country: "Spain",
    description: "Intimate 500-person festival on the banks of the Río Tajo in Toledo, Spain, with 90% of artists performing in Spain for the first time across Funktion One sound systems.",
    img: "https://imgproxy.ra.co/_/quality:66/aHR0cHM6Ly9zdGF0aWMucmEuY28vaW1hZ2VzL25ld3MvMjAyNS9yZnJjdHJfcHJfaW1nXzAxNC5qcGc=",
    tags: ["Electronic", "Techno", "Offgrid"],
  },
  // JUNE
  {
    name: "Wildheart Gathering",
    slug: "wildheart-gathering",
    start: "2026-06-04",
    end: "2026-06-07",
    location: "South Bohemia",
    country: "Czech Republic",
    description: "Summer gathering in South Bohemia for wild herb walks, movement, singing and campfire evenings. A beautiful re-wild event focused on self-care.",
    img: "https://www.beautifulgatherings.eu/wp-content/uploads/brizy/imgs/beautiful-Gatherings-7-983x553x0x0x983x552x1768145837.jpg",
    tags: ["Offgrid"],
  },
  {
    name: "Wurzelfestival",
    slug: "wurzelfestival",
    start: "2026-06-04",
    end: "2026-06-07",
    location: "Bavaria",
    country: "Germany",
    description: "Colourful electronic music festival in Bavaria. Community-driven event inspired by original Berlin club culture with participatory planning.",
    img: "/img/2019_04_19601215_1551493681587987_4157998990596320229_n.png",
    tags: ["Electronic"],
  },
  {
    name: "Art Baer Burn",
    slug: "art-baer-burn",
    start: "2026-06-11",
    end: "2026-06-14",
    location: "Brandenburg",
    country: "Germany",
    description: "Regional burn near Berlin celebrating art, community and play. Inspired by Burning Man since 1986 — a magical event for creation, connection and fun.",
    img: "/img/2024_06_art-baer-burn.jpg",
    tags: ["Burner", "Arts"],
  },
  {
    name: "Waking Life",
    slug: "waking-life",
    start: "2026-06-17",
    end: "2026-06-22",
    location: "Crato",
    country: "Portugal",
    description: "Not-for-profit participatory festival in Portugal promoting cultural and agricultural initiatives. Techno, experimental and electronic music in the sun.",
    img: "/img/2022_01_Waking-Life-Portugal.jpg",
    tags: ["Psytrance", "Techno", "Electronic"],
  },
  {
    name: "Tantric Joy Festival",
    slug: "tantric-joy-festival",
    start: "2026-06-17",
    end: "2026-06-21",
    location: "Amsterdam",
    country: "Netherlands",
    description: "5-day tantra festival near Amsterdam with 60 workshops, 6 temples, concerts and ecstatic dance. 400 participants and 30 international facilitators.",
    img: "/img/2025_11_tantra-joy-festival.png",
    tags: ["Mindfulness"],
  },
  {
    name: "Black Forest Ecstatic Dance Festival",
    slug: "black-forest-ecstatic-dance-festival",
    start: "2026-06-18",
    end: "2026-06-21",
    location: "Black Forest",
    country: "Germany",
    description: "4-day outdoor ecstatic dance festival in the Black Forest. Morning and evening dance, yoga, contact improvisation, campfires and forest bathing.",
    img: "/img/2025_01_black-forest-ecstatic-dance-festival.jpg",
    tags: ["Mindfulness"],
  },
  {
    name: "Solstice Festival",
    slug: "solstice-festival",
    start: "2026-06-18",
    end: "2026-06-20",
    location: "Ruka. Kuusamo",
    country: "Finland",
    description: "Electronic music festival in northern Finland near the Arctic Circle during midsummer, when the sun never sets. Three stages with picturesque views over lakes.",
    img: "/img/2024_12_solstice-festival.jpg",
    tags: ["Electronic", "Offgrid"],
  },
  {
    name: "Where the Sheep Sleep",
    slug: "where-the-sheep-sleep",
    start: "2026-06-18",
    end: "2026-06-22",
    location: "Flevoland",
    country: "Netherlands",
    description: "Burning Man-inspired gathering in the Netherlands. A massive immersive playground for four days of art, community and self-expression.",
    img: "/img/2020_03_where-the-sheep.jpg",
    tags: ["Burner", "Arts"],
  },
  {
    name: "Sónar Festival",
    slug: "snar-festival",
    start: "2026-06-18",
    end: "2026-06-20",
    location: "Barcelona",
    country: "Spain",
    description: "Sónar Festival is where raw electronic energy collides with underground culture, art, and relentless sound. Set in the industrial pulse of Barcelona, Sónar has built a reputation as one of the most forward-thinking festivals in the world.",
    img: "https://storage.googleapis.com/pro-cms-bucket/2662_Village_Martini_Ariel_20230615_f8ff91ebfc/2662_Village_Martini_Ariel_20230615_f8ff91ebfc.jpeg",
    tags: ["Electronic", "Techno"],
  },
  {
    name: "Everness Festival",
    slug: "everness-festival",
    start: "2026-06-19",
    end: "2026-06-28",
    location: "Bükk Hills",
    country: "Hungary",
    description: "Ten-day transformative gathering in Hungary's Bükk Hills. Workshops, meditation, music and community for awareness, recharge and deep connection.",
    img: "/img/2026_04_everness-festival.jpg",
    tags: ["Offgrid"],
  },
  {
    name: "Butiba Festival",
    slug: "butiba-festival",
    start: "2026-06-21",
    end: "2026-06-24",
    location: "Sigulda",
    country: "Latvia",
    description: "Summer solstice festival in Latvia celebrating joy, healing and community. Music, ceremonies, rituals and sacred musicians during four days of solstice.",
    img: "/img/2026_03_butiba-festival.jpg",
    tags: ["Arts"],
  },
  {
    name: "Pachamama Play Festival",
    slug: "pachamama-play-festival",
    start: "2026-06-21",
    end: "2026-07-04",
    location: "Bay of Kotor",
    country: "Montenegro",
    description: "Intimate 40-person gathering at Pachamama Farm, Montenegro for AcroYoga, yoga, meditation and beach time. Alcohol and drug-free over one or two weeks.",
    img: "/img/2026_01_Acro-Festival-montegro-pachamama.jpg",
    tags: ["Mindfulness"],
  },
  {
    name: "Kiez Burn",
    slug: "kiez-burn",
    start: "2026-06-23",
    end: "2026-06-29",
    location: "Brandenburg",
    country: "Germany",
    description: "Five-day Burning Man-inspired event in Brandenburg celebrating self-expression and creativity. No fixed programme — all content contributed by attendees.",
    img: "/img/2024_04_o37kfb.jpg",
    tags: ["Burner", "Arts"],
  },
  {
    name: "UFO Bufo Festival",
    slug: "ufo-bufo-festival",
    start: "2026-06-24",
    end: "2026-06-28",
    location: "South Bohemia",
    country: "Czech Republic",
    description: "Czech psytrance festival since 2013 with natural digital detox — no mobile coverage. Strictly non-commercial, no ads or sponsor logos.",
    img: "/img/2017_05_91970206_1632558423548958_8290940246120464384_o-scaled.jpg",
    tags: ["Offgrid"],
  },
  {
    name: "Burning Mountain Festival",
    slug: "burning-mountain-festival",
    start: "2026-06-25",
    end: "2026-06-28",
    location: "Graubünden, Swiss Alps",
    country: "Switzerland",
    description: "Psytrance festival at 1500m in the Swiss Alps. Campsite by the River Inn in the Engadine valley with flamethrowers, fire installations and top-tier lineups.",
    img: "/img/2024_04_burningmountain23_0022-L.jpg",
    tags: ["Burner", "Arts"],
  },
  {
    name: "Château Perché Festival",
    slug: "chteau-perch-festival",
    start: "2026-06-25",
    end: "2026-07-06",
    location: "Bouville",
    country: "France",
    description: "Enchanted castle rave in central France. Deep house and techno in a 200-artist, 3-day celebration of electronic music and alternative arts since 2015.",
    img: "/img/2023_01_Untitled-design-26.jpg",
    tags: ["Techno", "Electronic"],
  },
  {
    name: "Django Reinhardt Jazz Festival",
    slug: "django-reinhardt-jazz-festival",
    start: "2026-06-25",
    end: "2026-06-28",
    location: "Samois-sur-Seine",
    country: "France",
    description: "4-day jazz festival in the Château de Fontainebleau Park, France. Honouring Django Reinhardt's swing and modernity with gypsy jazz icons and young talents.",
    img: "/img/2016_02_djangoreinhardtfestival.png",
    tags: ["World Music"],
  },
  {
    name: "Masters of Calm Festival",
    slug: "masters-of-calm-festival",
    start: "2026-06-26",
    end: "2026-07-05",
    location: "Molėtai",
    country: "Lithuania",
    description: "Forest festival in Lithuania for 10 days of workshops, music, yoga and adventure. Balanced for families, couples and solo travellers in pine forest nature.",
    img: "/img/2020_02_mastersofcalm-2.jpg",
    tags: ["Offgrid"],
  },
  {
    name: "Soria Gathering",
    slug: "soria-gathering",
    start: "2026-06-26",
    end: "2026-06-30",
    location: "Sørøya island",
    country: "Norway",
    description: "Electronic music festival on the Norwegian islands in the midnight sun. Dance floors, fire, art and bass — a pilgrimage to the north where the sun never sets.",
    img: "/img/2024_04_360087078_655286239974534_7032700436994179345_n-edited.webp",
    tags: ["Electronic", "Offgrid"],
  },
  {
    name: "Nest Microfest",
    slug: "nest-microfest",
    start: "2026-06-12",
    end: "2026-06-14",
    location: "Pontons, Barcelona",
    country: "Spain",
    description: "Micro-festival in the vineyards and pine forests of Alt Penedès, one hour outside Barcelona, with three stages powered by custom BORIS Soundsystems and a retreat spirit.",
    img: "https://res.cloudinary.com/shotgun/image/upload/c_limit,w_1200,h_630/f_jpg/q_auto/production/artworks/Nest5Home_z2kiik.png",
    tags: ["Electronic", "Techno", "Offgrid"],
  },
  {
    name: "Fusion Festival",
    slug: "fusion-festival",
    start: "2026-06-24",
    end: "2026-06-28",
    location: "Lärz",
    country: "Germany",
    description: "Europe's legendary non-commercial cultural gathering on a former Soviet airbase in Lärz, Germany — volunteer-run, sponsor-free, and defined by radical creativity.",
    img: "https://cloudfront-eu-central-1.images.arcpublishing.com/madsack/QRGD2IYG6NFURI3ZNB3OMVSWMA.jpg",
    tags: ["Electronic", "Techno", "Psytrance", "Burner", "Arts"],
  },
  {
    name: "Friends of Friends Festival",
    slug: "friends-of-friends-festival",
    start: "2026-06-26",
    end: "2026-06-28",
    location: "London Waterloo",
    country: "UK",
    description: "Independent electronic music gathering in a lakeside forest setting celebrating inclusivity and diversity, blending house, techno, jungle, and live bands.",
    img: "https://fixr-cdn.fixr.co/images/event/2025-11/1cc5bbdb92d34e60b49029ad416ee53c.jpeg",
    tags: ["Electronic", "Mindfulness", "Burner", "Arts"],
  },
  // JULY
  {
    name: "Bear Stone Festival",
    slug: "bear-stone-festival",
    start: "2026-07-02",
    end: "2026-07-05",
    location: "Mrežnica river",
    country: "Croatia",
    description: "Psychedelic, heavy rock and electronic festival on Croatia's Mrežnica river. Stunning art installations, live bands and DJ sets in a vibrant dreamland.",
    img: "/img/2024_04_Logo2026_500-1.png",
    tags: ["Arts", "Electronic"],
  },
  {
    name: "Rampage Open Air",
    slug: "rampage-open-air",
    start: "2026-07-02",
    end: "2026-07-05",
    location: "Werchter",
    country: "Belgium",
    description: "Biggest drum and bass and dubstep festival in the universe. Two days of bass music in Werchter, Belgium with 30+ artists shaking the arena.",
    img: "/img/2020_04_56764491_10161740629060051_4637088052743766016_o.jpg",
    tags: ["Electronic"],
  },
  {
    name: "Third Eye Festival",
    slug: "third-eye-festival",
    start: "2026-07-03",
    end: "2026-07-06",
    location: "South of Berlin",
    country: "Germany",
    description: "Electronic music and arts festival in the forest south of Berlin. Techno, ambient, yoga, meditation and visual art for self-discovery and healing.",
    img: "/img/2024_12_third-eye-festival-1024x1024.jpg",
    tags: ["Techno", "Electronic"],
  },
  {
    name: "Surya Spirits Festival",
    slug: "surya-spirits-festival",
    start: "2026-07-03",
    end: "2026-07-06",
    location: "Ardennes",
    country: "Belgium",
    description: "Psytrance and wellness fusion festival in the endless woods of the Ardennes, Belgium. Daytime, family-friendly and close to Ghent in a gorgeous natural setting.",
    img: "/img/2023_04_location-04-frame-1-e1680645318330.png",
    tags: ["Psytrance", "Mindfulness"],
  },
  {
    name: "Lithica Gathering",
    slug: "lithica-gathering",
    start: "2026-07-06",
    end: "2026-07-12",
    location: "Svalbard",
    country: "Norway",
    description: "Wild human rewilding experiment in Norway. Multi-generational clan living in pristine nature — a gathering to reclaim wild spaces for wild humans.",
    img: "/img/2023_03_lithica-gathering.webp",
    tags: ["Offgrid"],
  },
  {
    name: "Elsewhere Festival",
    slug: "elsewhere-festival",
    start: "2026-07-07",
    end: "2026-07-12",
    location: "Zaragoza",
    country: "Spain",
    description: "Formerly Nowhere Festival — Spain's Burning Man in the desert of Northern Spain. Week of music, art installations, self-expression and radical self-reliance.",
    img: "/img/2016_01_05-nowhere-spain-burningman-alternatives.jpg",
    tags: ["Burner", "Arts"],
  },
  {
    name: "Slot Art Festival",
    slug: "slot-art-festival",
    start: "2026-07-08",
    end: "2026-07-12",
    location: "Lubiąż monastery",
    country: "Poland",
    description: "Five-day alternative culture festival inside a Polish monastery. Punk rock, Christian spirituality and independent art over dozens of workshops and concerts.",
    img: "/img/2016_02_slotartfestival.jpg",
    tags: ["Arts"],
  },
  {
    name: "Body Love Festival",
    slug: "body-love-festival",
    start: "2026-07-09",
    end: "2026-07-13",
    location: "Bavaria",
    country: "Germany",
    description: "Weekend festival of ecstatic dance, contact improv and twerk/yoga with live music in a former Botanic Garden eco-village, 90 minutes from Berlin.",
    img: "/img/2025_02_bodylovefestival.jpg",
    tags: ["Mindfulness"],
  },
  {
    name: "Into the Woods Festival",
    slug: "into-the-woods-festival",
    start: "2026-07-09",
    end: "2026-07-11",
    location: "Dalarna",
    country: "Sweden",
    description: "Off-grid electronic and world music festival deep in the Swedish forest. Floating sauna, beautiful lake stage, sustainable energy and diverse workshops.",
    img: "/img/2024_12_into-the-woods.jpg",
    tags: ["Offgrid"],
  },
  {
    name: "Kosmos Festival",
    slug: "kosmos-festival",
    start: "2026-07-09",
    end: "2026-07-12",
    location: "Suomussalmi",
    country: "Finland",
    description: "Popular electronic and psytrance festival in Finnish nature. Drum and bass, techno, psytrance and suomisaundi with healing and circus shows.",
    img: "/img/2018_01_kosmos-eventti-2-1024x536-1.png",
    tags: ["Electronic", "Psytrance"],
  },
  {
    name: "Ritual Gatherings",
    slug: "ritual-gatherings",
    start: "2026-07-10",
    end: "2026-07-12",
    location: "Sinemorets beach",
    country: "Bulgaria",
    description: "Intimate beach festival on Bulgaria's Black Sea coast. Music, art, food and mindfulness from friends for friends in a stunning cape setting.",
    img: "/img/2024_12_ritual-gatherings.jpg",
    tags: ["Electronic"],
  },
  {
    name: "Awakenings Festival",
    slug: "awakenings-festival",
    start: "2026-07-10",
    end: "2026-07-12",
    location: "Hilvarenbeek",
    country: "Netherlands",
    description: "Awakenings Festival is the ultimate techno holiday! The festival grounds at Hilvarenbeek are the perfect backdrop for a weekend full of new discoveries, memories and a lot of techno madness. With 80.000 visitors from over 80 countries in a weekend Awakenings Festival is the highlight of Europe's techno music calendar.",
    img: "https://assets.awakenings.com/images/transforms/blocks/_929x522_crop_center-center_none/2018-07-01_Awakenings_festival_352.jpg",
    tags: ["Electronic", "Techno"],
  },
  {
    name: "Caia Tribe Gathering",
    slug: "caia-tribe-gathering",
    start: "2026-07-15",
    end: "2026-07-19",
    location: "Steyerberg",
    country: "Germany",
    description: "Holistic gathering of 300 at one of Germany's oldest eco-villages. Ecstatic dance, yoga, breathwork, cacao ceremony and organic food in Steyerberg.",
    img: "/img/2023_11_KatharinaBauerPhotography__CaiaGathering_2023_DSC07718-Gros.jpeg",
    tags: ["Mindfulness"],
  },
  {
    name: "Kolorádó Festival",
    slug: "kolord-festival",
    start: "2026-07-15",
    end: "2026-07-17",
    location: "Mátra mountains",
    country: "Hungary",
    description: "Signal-free festival in Hungary's Mátra mountains near Budapest. Switch off and enjoy culture, camping, forest adventures and community vibes.",
    img: "/img/2022_01_Kolorado-Hungary.jpg",
    tags: ["Offgrid"],
  },
  {
    name: "Electric Castle Festival",
    slug: "electric-castle-festival",
    start: "2026-07-16",
    end: "2026-07-19",
    location: "Bánffy Castle, Bonțida",
    country: "Romania",
    description: "Five-day electronic music festival at the 15th-century Bánffy Castle in Transylvania, Romania. 250+ artists, new media installations and 24/7 camping.",
    img: "/img/2020_04_Electric-Castle-photo-Electric-Castle-on-FB.jpg",
    tags: ["Electronic"],
  },
  {
    name: "Yaga Gathering",
    slug: "yaga-gathering",
    start: "2026-07-16",
    end: "2026-07-20",
    location: "Šilutė district",
    country: "Lithuania",
    description: "Psychedelic open-air gathering in Lithuania since 2003. Alternative lifestyle, trance, healing arts, electronic music and holistic therapy.",
    img: "/img/2016_01_Yaga_09_24_Day1_0029.jpg",
    tags: ["Psytrance"],
  },
  {
    name: "Road Junky Festival of Creativity",
    slug: "road-junky-festival-of-creativity",
    start: "2026-07-17",
    end: "2026-07-26",
    location: "South Bohemia hills",
    country: "Czech Republic",
    description: "Intimate 125-person creative festival in Czech forest hills. All-inclusive week of workshops from dance to fire-making, nightly campfire singing.",
    img: "/img/2021_09_satfestivalfirebannerstyle.jpg",
    tags: ["Arts", "Offgrid"],
  },
  {
    name: "Borderland",
    slug: "borderland",
    start: "2026-07-20",
    end: "2026-07-26",
    location: "Skåne",
    country: "Sweden",
    description: "Swedish co-created gathering run by participants, not spectators. Hugs are currency, places by lottery — a week of community and creativity.",
    img: "/img/2016_01_borderland_logo2015.png",
    tags: ["Burner", "Arts"],
  },
  {
    name: "Polifonic Festival",
    slug: "polifonic-festival",
    start: "2026-07-22",
    end: "2026-07-26",
    location: "Tropea, Calabria",
    country: "Italy",
    description: "Electronic music festival in Tropea, Calabria promoting diversity and community. Disco, house, techno and beyond with a Mediterranean twist.",
    img: "/img/2022_01_Polifonic-Italy.jpg",
    tags: ["Electronic"],
  },
  {
    name: "Feel Festival",
    slug: "feel-festival",
    start: "2026-07-23",
    end: "2026-07-26",
    location: "Groß Köris",
    country: "Germany",
    description: "Music and arts festival near Berlin with 10 stages, yoga, meditation and art workshops. Half-pipe skateboarding and beautiful beach lakes nearby.",
    img: "/img/2019_04_Blackwork_2017_07_07_Feel_PDB5317.jpeg",
    tags: ["Mindfulness", "Arts"],
  },
  {
    name: "Ozora Psychedelic Festival",
    slug: "ozora-psychedelic-festival",
    start: "2026-07-24",
    end: "2026-08-04",
    location: "Dádpuszta",
    country: "Hungary",
    description: "Hungary's biggest psychedelic tribal gathering in Dádpuszta. One week of psytrance, massive art constructions and thousands of interesting people.",
    img: "https://discover-festivals.vercel.app/img/OZORA_Festival.jpg",
    tags: ["Psytrance"],
  },
  {
    name: "Castlefest",
    slug: "castlefest",
    start: "2026-07-30",
    end: "2026-08-02",
    location: "Lisse",
    country: "Netherlands",
    description: "Fantasy festival at Keukenhof Castle in Lisse, Netherlands. Young and old enter the Other World of medieval crafts, music and fantasy culture.",
    img: "/img/2022_02_Castlefest-Netherlands.jpg",
    tags: ["Arts", "World Music"],
  },
  {
    name: "Fengaros Festival",
    slug: "fengaros-festival",
    start: "2026-07-30",
    end: "2026-08-01",
    location: "Kato Drys",
    country: "Cyprus",
    description: "Annual music village festival in the Cypriot village of Kato Drys. Workshops in rhythm, voice, modal composition and improvisation for all levels.",
    img: "/img/2024_04_f4-203-0a6e0adf-558w.webp",
    tags: ["World Music", "Arts"],
  },
  {
    name: "Hors Sol Festival",
    slug: "hors-sol-festival",
    start: "2026-07-02",
    end: "2026-07-05",
    location: "Cévennes",
    country: "France",
    description: "Self-financed 500-person gathering on France's Causse Noir plateau in the Cévennes, merging electronic music and visual art with collective rituals at human scale.",
    img: "https://res.cloudinary.com/shotgun/image/upload/c_limit,w_3840/fl_lossy/f_auto/q_auto/production/artworks/Design_sans_titre_5_rzo1xa.png",
    tags: ["Electronic", "Techno", "Offgrid", "Arts"],
  },
  {
    name: "Pohoda Festival",
    slug: "pohoda-festival",
    start: "2026-07-08",
    end: "2026-07-11",
    location: "Trenčín",
    country: "Slovakia",
    description: "Slovakia's largest festival on a former military airfield in Trenčín, with 30,000 daily attendees across 15 stages spanning rock, electronic, jazz, world music and more.",
    img: "https://www.pohodafestival.sk/og_image.2023.jpg",
    tags: ["Electronic", "World Music", "Arts", "Mindfulness"],
  },
  {
    name: "Nation of Gondwana",
    slug: "nation-of-gondwana",
    start: "2026-07-16",
    end: "2026-07-19",
    location: "Nauen",
    country: "Germany",
    description: "One of Germany's oldest electronic music festivals since 1995, with 10,000 visitors at a lakeside venue near Nauen and four stages dedicated exclusively to techno.",
    img: "https://groove.de/wp-content/uploads/2021/07/Nation.of_.Gondwana.2021.Foto_.A.Waltz_.DSCF7742.jpeg",
    tags: ["Electronic", "Techno"],
  },
  {
    name: "Mit Dir Festival",
    slug: "mit-dir-festival",
    start: "2026-07-23",
    end: "2026-07-26",
    location: "Friedland",
    country: "Germany",
    description: "Intimate 2,500-person festival near Eisenhüttenstadt running since 2016, with six stages, a lakeside setting, and community-first pricing.",
    img: "https://berlin-enjoy.com/wp-content/uploads/2024/07/Mit-Dir-Festival-2024-Muhle.webp",
    tags: ["Electronic", "Techno", "Offgrid"],
  },
  {
    name: "Wabi Sabi Festival",
    slug: "wabi-sabi-festival",
    start: "2026-07-24",
    end: "2026-07-26",
    location: "Vaas",
    country: "France",
    description: "Volunteer-run micro-festival set within 18th-century ruins in the Sologne region of France, transforming a crumbling historical site into a stage for underground techno.",
    img: "https://imgproxy.ra.co/_/quality:66/aHR0cHM6Ly9pbWFnZXMucmEuY28vZjczY2RlZTdhODRlOTRiODBlMWYxZmNhOGNmYWYwODM3ZGFmYWNiYi5qcGc=",
    tags: ["Electronic", "Techno", "Offgrid"],
  },
  {
    name: "Doel Festival",
    slug: "doel-festival",
    start: "2026-07-25",
    end: "2026-07-25",
    location: "Doel (Beveren)",
    country: "Belgium",
    description: "One-day festival in the near-deserted Belgian ghost town of Doel, where empty houses become stages for electronic music and art.",
    img: "https://ket.brussels/wp-content/uploads/2026/03/Capture-decran-2026-03-23-094752.jpg",
    tags: ["Electronic", "Techno"],
  },
  {
    name: "Prærie Festival",
    slug: "prrie-festival",
    start: "2026-07-30",
    end: "2026-08-02",
    location: "Galenbeck",
    country: "Germany",
    description: "Community-run 2,000-person festival in Galenbeck, Mecklenburg, with over 100 acts across four stages of open-air techno and electronic, a swimming lake, and warm-hearted people.",
    img: "https://i.ytimg.com/vi/eCRVQdXS4Rc/maxresdefault.jpg",
    tags: ["Electronic", "Techno", "Offgrid"],
  },
  {
    name: "Garbicz Festival",
    slug: "garbicz-festival",
    start: "2026-07-30",
    end: "2026-08-03",
    location: "Garbicz",
    country: "Poland",
    description: "Boutique lakeside festival in a Polish forest near the German border, with a community feel built on deep melodic techno and environmental stewardship.",
    img: "https://www.beatheim.com/wp-content/uploads/2024/07/Garbicz-Festival-Photo-Policy-2024.jpg",
    tags: ["Electronic", "Techno", "Psytrance"],
  },
  // AUGUST
  {
    name: "MO:DEM Festival",
    slug: "modem-festival",
    start: "2026-08-03",
    end: "2026-08-09",
    location: "Zrmanja canyon",
    country: "Croatia",
    description: "Psychedelic electronic festival in Croatia's Zrmanja canyon. Years of unforgettable experiences combining psytrance, visuals and community spirit.",
    img: "/img/2017_07_123770640_3498696346872672_4439305078199450544_n.jpg",
    tags: ["Psytrance"],
  },
  {
    name: "Pyramid Festival",
    slug: "pyramid-festival",
    start: "2026-08-03",
    end: "2026-08-09",
    location: "Rtanj Mountain",
    country: "Serbia",
    description: "Festival at the foot of Serbia's mystical Rtanj Mountain. A community-shaped gathering blending music, ritual, art and nature over several days.",
    img: "/img/2026_02_PYRAMID-KV-01.png",
    tags: ["Offgrid"],
  },
  {
    name: "Healing Festival",
    slug: "healing-festival",
    start: "2026-08-05",
    end: "2026-08-09",
    location: "South Bohemia",
    country: "Czech Republic",
    description: "5-day wellness festival in South Bohemia with 150+ workshops, yoga, ecstatic dance, cold therapy and ceremonies. Inspiration, joy and personal transformation.",
    img: "/img/2024_04_ceremonie-1536x1024-1.jpg",
    tags: ["Mindfulness"],
  },
  {
    name: "Ancient Trance Festival",
    slug: "ancient-trance-festival",
    start: "2026-08-06",
    end: "2026-08-09",
    location: "Saxony",
    country: "Germany",
    description: "Celebration of ancient music fused with electronics in Saxony. Jaw harps, shamanic roots and modern ecstatic world music in a space of love and community.",
    img: "/img/2017_01_ancientrancefestival.jpg",
    tags: ["World Music", "Electronic"],
  },
  {
    name: "Ecstatica Festival",
    slug: "ecstatica-festival",
    start: "2026-08-08",
    end: "2026-08-11",
    location: "Hainburg an der Donau",
    country: "Austria",
    description: "Ecstatic dance festival in an ecovillage on the Austria-Slovakia border. Breathwork, live music, sound healing and conscious connection in Central Europe.",
    img: "/img/2024_04_rsw_740cg_truem.webp",
    tags: ["Mindfulness"],
  },
  {
    name: "Convento Festival",
    slug: "convento-festival",
    start: "2026-08-09",
    end: "2026-08-14",
    location: "Tuscany",
    country: "Italy",
    description: "5-day retreat in an ancient Tuscany monastery. Movement, sound, breath and presence workshops for around 100 participants in the sacred hills.",
    img: "https://festivalsandretreats.com/wp-content/uploads/2026/01/Convento-Festival-Casola-Italien-August-2025-©-mio-schweiger-1402-scaled.jpg",
    tags: ["Mindfulness", "Offgrid"],
  },
  {
    name: "Sizigia Eclipse Festival",
    slug: "sizigia-eclipse-festival",
    start: "2026-08-10",
    end: "2026-08-14",
    location: "Andalusia",
    country: "Spain",
    description: "Electronic festival in Andalusia during Spain's August 2026 total solar eclipse. Music and dance beneath the celestial alignment of sun, moon and earth.",
    img: "/img/2026_01_sizigia-fetival-eclipse.jpg",
    tags: ["Electronic"],
  },
  {
    name: "Boomtown Fair",
    slug: "boomtown-fair",
    start: "2026-08-12",
    end: "2026-08-16",
    location: "Matterley Estate, Winchester",
    country: "England",
    description: "Conceptual UK festival imagined as a city with its own mythology, politics and evolution. 4 days of themed districts, music and immersive theatre in Winchester.",
    img: "/img/2016_02_boomtownfestival.jpg",
    tags: ["Arts", "Electronic"],
  },
  {
    name: "Iceland Eclipse",
    slug: "iceland-eclipse",
    start: "2026-08-12",
    end: "2026-08-15",
    location: "Iceland",
    country: "Iceland",
    description: "4-day immersive festival in Iceland during the 2026 total eclipse. Visionaries, artists and eclipse seekers at the intersection of music and wellness.",
    img: "/img/2026_01_iceland-eclipse-festival.jpeg",
    tags: ["Mindfulness", "Offgrid"],
  },
  {
    name: "Roztoč Fest",
    slug: "rozto-fest",
    start: "2026-08-13",
    end: "2026-08-17",
    location: "Moravia",
    country: "Czech Republic",
    description: "Czech flow arts and live music festival for circus artists, fire dancers, actors and performers. Live DJs, workshops, huge shows and all-night firejams.",
    img: "/img/2024_04_fan-workshop-2048x1367-1.webp",
    tags: ["Arts"],
  },
  {
    name: "New Healing Festival",
    slug: "new-healing-festival",
    start: "2026-08-17",
    end: "2026-08-23",
    location: "Mecklenburg",
    country: "Germany",
    description: "Family-friendly alternative festival in Mecklenburg with meditation, yoga, ceremonies and electronic music nights. Community gathering for personal development.",
    img: "/img/2019_04_55823744_1267947103371559_4379219186954534912_o.jpg",
    tags: ["Mindfulness"],
  },
  {
    name: "Green Man Festival",
    slug: "green-man-festival",
    start: "2026-08-20",
    end: "2026-08-23",
    location: "Glanusk Park, Brecon Beacons",
    country: "Wales",
    description: "Independent alternative music festival in Wales' Brecon Beacons. Indie, psych, folk and electronica across 17 stages with 1500 multi-arts acts and bonfires.",
    img: "/img/2016_02_greenman.png",
    tags: ["Arts"],
  },
  {
    name: "Lost Village",
    slug: "lost-village",
    start: "2026-08-27",
    end: "2026-08-30",
    location: "Lincolnshire",
    country: "UK",
    description: "Intimate electronic music festival in an abandoned Lincolnshire forest. Explore derelict houses, overgrown courtyards and an abandoned airport.",
    img: "/img/2022_01_Lost-Village-England.jpg",
    tags: ["Electronic"],
  },
  {
    name: "Shambala Festival",
    slug: "shambala-festival",
    start: "2026-08-27",
    end: "2026-08-30",
    location: "Northamptonshire",
    country: "UK",
    description: "Diverse UK festival in Northamptonshire. 200+ musical acts, cabaret, workshops, comedy, circus and poetry over four days at a secret countryside location.",
    img: "/img/2016_02_the_kids_area09_website_image_voek_standard-1.jpg",
    tags: ["Arts"],
  },
  {
    name: "Evolve Festival",
    slug: "evolve-festival",
    start: "2026-08-27",
    end: "2026-08-30",
    location: "Helenesee",
    country: "Germany",
    description: "Weekend festival at Helenesee, Germany where yoga, personal growth and ceremonies meet music and dance. Workshops, healing and multiple stages lakeside.",
    img: "https://framerusercontent.com/images/PmLlOVDwD3sjijDHdeWz2cpReM.gif",
    tags: ["Mindfulness"],
  },
  {
    name: "Hütte in the Forest",
    slug: "htte-in-the-forest",
    start: "2026-08-05",
    end: "2026-08-09",
    location: "Château d'Etangsannes",
    country: "France",
    description: "Independent four-day festival around a French château blending psychedelic and dance-driven electronic music with visual arts, creative workshops, and artist residencies.",
    img: "https://static.ra.co/images/promoter/cover/fr-hutteintheforest.jpg?dateUpdated=1776763718923",
    tags: ["Electronic", "Offgrid", "Arts"],
  },
  {
    name: "CRX Festival",
    slug: "crx-festival",
    start: "2026-08-07",
    end: "2026-08-08",
    location: "Cave di Fantano, Grottaglie",
    country: "Italy",
    description: "Laboratory-festival transforming ancient stone quarries in Grottaglie, Puglia into a resonant venue where experimental electronic sound and international club culture merge.",
    img: "https://images.xceed.me/events/banners/crx-festival-2026-full-pass-grottaglie-xceed-7633.jpg?w=1920&h=1440&ar=4:3&fm=auto",
    tags: ["Electronic", "Techno", "Offgrid", "Arts", "World Music"],
  },
  {
    name: "Fata Morgana Festival",
    slug: "fata-morgana-festival",
    start: "2026-08-07",
    end: "2026-08-10",
    location: "Coutarnoux",
    country: "France",
    description: "Multidisciplinary festival under the vast limestone vaults of an abandoned Burgundy quarry, blending techno, dub, experimental and trance with contemporary art and workshops.",
    img: "https://res.cloudinary.com/shotgun/image/upload/c_limit,w_3840/fl_lossy/f_auto/q_auto/c_limit,f_auto,fl_lossy,q_auto,w_1920/v1767948122/production/artworks/260104_FMF_26_VISU_AFFICHE_1920X1080_gsjara",
    tags: ["Electronic", "Techno", "Offgrid", "Arts"],
  },
  {
    name: "Bucht der Träumer",
    slug: "bucht-der-trumer",
    start: "2026-08-13",
    end: "2026-08-17",
    location: "Helenesee / Frankfurt (Oder)",
    country: "Germany",
    description: "Four-to-five day electronic festival at Lake Helenesee near Berlin with 13,000 attendees, spanning techno, house, psytrance and rap alongside workshops, a sauna, and Psycare.",
    img: "https://i0.wp.com/bucht-der-traeumer.de/wp-content/uploads/2025/09/20250816_BdT25_Ponybarker_Atlantis_HorstHaller_FridaDarko-02620-1.jpg?fit=2500%2C1667&ssl=1",
    tags: ["Electronic", "Techno", "Burner", "Offgrid", "Arts"],
  },
  {
    name: "Nemora Fest",
    slug: "nemora-fest",
    start: "2026-08-27",
    end: "2026-08-30",
    location: "Torre Alfina, Lazio",
    country: "Italy",
    description: "Nascent festival at the enchanted Bosco del Sasseto forest in Torre Alfina, Lazio — called 'The Snow White Wood' by National Geographic — blending sound, performance and gardening.",
    img: "https://res.cloudinary.com/dglrghiom/image/upload/v1779621897/Nemora_fest_axt87p.jpg",
    tags: ["Electronic", "Techno", "Offgrid"],
  },
  {
    name: "Schwing und Stampf Festival",
    slug: "schwing-und-stampf-festival",
    start: "2026-08-27",
    end: "2026-08-30",
    location: "Wolfenschiessen",
    country: "Switzerland",
    description: "Non-profit Swiss alpine festival at 900 metres elevation near Lucerne, run by five local music labels, with two distinct stages and radical inclusivity in a forest and meadow setting.",
    img: "https://ubwg.ch/wp-content/uploads/2025/06/schwingstampf_impression_4-1024x682.jpeg",
    tags: ["Electronic", "Techno", "Offgrid", "Arts"],
  },
  // SEPTEMBER
  {
    name: "Kama Etna Festival",
    slug: "kama-etna-festival",
    start: "2026-09-01",
    end: "2026-09-06",
    location: "Mount Etna, Sicily",
    country: "Italy",
    description: "Immersive arts and intimacy festival on Sicily's Mount Etna. A celebration of Eros, art and humanity where pleasure, expression and connection are honored.",
    img: "/img/2025_06_WhatsApp-Image-2025-05-29-at-22.07.12.jpeg",
    tags: ["Mindfulness"],
  },
  {
    name: "Own Spirit Festival",
    slug: "own-spirit-festival",
    start: "2026-09-02",
    end: "2026-09-07",
    location: "Huesca, Aragon",
    country: "Spain",
    description: "Visionary psytrance festival in Huesca, Spain. Psychedelic culture, community and dance as spiritual expression. Two 24-hour stages, family-friendly.",
    img: "/img/2016_02_11427787_454813438029069_3897174652792562629_n.jpg",
    tags: ["Psytrance"],
  },
  {
    name: "The Island Festival",
    slug: "the-island-festival",
    start: "2026-09-03",
    end: "2026-09-07",
    location: "Obonjan island",
    country: "Croatia",
    description: "Five-day festival on the private Croatian island of Obonjan. Electronic music, stunning venues, wellness, culinary delights and crystal-clear sea swimming.",
    img: "/img/2022_01_The-Island-Festival-Croatia.jpg",
    tags: ["Electronic"],
  },
  {
    name: "at.tension",
    slug: "attension",
    start: "2026-09-03",
    end: "2026-09-06",
    location: "Lärz airfield",
    country: "Germany",
    description: "Interdisciplinary theatre festival across 100 hectares of a former airfield in Lärz, Germany. Aeroplane hangars, landing strip and circus tents.",
    img: "/img/2022_02_at.tension-Germany.jpeg",
    tags: ["Arts"],
  },
  {
    name: "Space Safari",
    slug: "space-safari",
    start: "2026-09-04",
    end: "2026-09-07",
    location: "Ardennes",
    country: "Belgium",
    description: "Psychedelic trance festival in the Ardennes Forest, Belgium. Multi-dimensional journey of psytrance music, expressive dance and visual wonders.",
    img: "/img/2020_01_spacesafari.jpg",
    tags: ["Psytrance", "Offgrid"],
  },
  {
    name: "Portugal Contact Festival",
    slug: "portugal-contact-festival",
    start: "2026-09-14",
    end: "2026-09-19",
    location: "Alentejo",
    country: "Portugal",
    description: "Contact improvisation music festival in Portugal's Alentejo nature. Dance on the beach and ocean with international teachers for 6 days of movement.",
    img: "/img/2024_04_Quinta-Braz-Meeting-chill-scaled-1.jpg",
    tags: ["Mindfulness", "Offgrid"],
  },
  {
    name: "Mystic Creatures",
    slug: "mystic-creatures",
    start: "2026-09-03",
    end: "2026-09-07",
    location: "Złocieniec",
    country: "Poland",
    description: "Four-day festival on a forested island in Złocieniec, Poland, with six stages spanning progressive house, techno, psy-techno and ambient, plus art installations.",
    img: "https://res.cloudinary.com/dglrghiom/image/upload/v1779622073/Mystic_Creations_clsgop.jpg",
    tags: ["Electronic", "Techno", "Arts"],
  },
  {
    name: "Komorebi Music Festival",
    slug: "komorebi-music-festival",
    start: "2026-09-04",
    end: "2026-09-06",
    location: "Forte di Vinadio (CN)",
    country: "Italy",
    description: "Three-day electronic festival at the historic Forte di Vinadio in the Piedmont Alps, where sound, nature and performative arts merge within the fort's panoramic alpine architecture.",
    img: "https://images.xceed.me/events/banners/komorebi-music-festival-2026-3-days-pass-cuneo-xceed-171b.jpg?w=1200&h=630&ar=16:9&fm=auto",
    tags: ["Electronic", "Techno", "Arts"],
  },
  {
    name: "Eternal Sun Festival",
    slug: "eternal-sun-festival",
    start: "2026-09-04",
    end: "2026-09-06",
    location: "Sougia, Crete",
    country: "Greece",
    description: "Intimate 500-guest electronic festival in the remote seaside village of Sougia on Crete's southern coast, combining sunset-to-sunrise sessions with Mediterranean village life.",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCLsmc0KnEi-N3uZCQK_f339xowxePm9KkEQ&s",
    tags: ["Electronic", "Techno", "Offgrid"],
  },
  // JUNE (added)
  {
    name: "Kala Festival",
    slug: "kala-festival",
    start: "2026-06-03",
    end: "2026-06-10",
    location: "Dhërmi",
    country: "Albania",
    description: "A week-long boutique festival on the Albanian Riviera merging underground electronic music with Mediterranean sun and sea.",
    img: "https://imgproxy.ra.co/_/quality:66/aHR0cHM6Ly9zdGF0aWMucmEuY28vaW1hZ2VzL25ld3MvMjAyNi9rYWxhZmVzdGl2YWwuanBlZw==",
    tags: ["Electronic", "Techno"],
  },
  {
    name: "PÁVOIA Festival",
    slug: "pvoia-festival",
    start: "2026-06-05",
    end: "2026-06-08",
    location: "Debrznica",
    country: "Poland",
    description: "Intimate 500-person electronic festival at a 19th-century manor park near the German border, one hour from Berlin.",
    img: "https://i0.wp.com/www.fazemag.de/wp-content/uploads/2022/02/JPbeutin_PAVOIA-289.jpeg?fit=640%2C395&ssl=1",
    tags: ["Electronic", "Techno", "Offgrid"],
  },
  // JULY (added)
  {
    name: "Silva Festival",
    slug: "silva-festival",
    start: "2026-07-09",
    end: "2026-07-11",
    location: "Unnaryd",
    country: "Sweden",
    description: "Off-grid electronic and world music festival deep in the Swedish forest. Floating sauna, beautiful lake stage, sustainable energy and diverse workshops.",
    img: "https://scontent-fra5-1.cdninstagram.com/v/t51.82787-15/684634320_18583069423048040_7351275168126651348_n.jpg?stp=dst-jpg_e35_s1080x1080_tt6&_nc_cat=110&ig_cache_key=Mzg5MDM5OTkwMDgzODc1NzE2NA%3D%3D.3-ccb7-5&ccb=7-5&_nc_sid=58cdad&efg=eyJ2ZW5jb2RlX3RhZyI6IkNBUk9VU0VMX0lURU0ueHBpZHMuMTQ0MC5zZHIucmVndWxhcl9waG90by5DMyJ9&_nc_ohc=z-UIIdI6-ewQ7kNvwG4oBJa&_nc_oc=AdpURA202nUjf2wfyKnKb9ELVkbaKc0Mw0HtB8Jffdx6l2tQ1IzpdOQ1S9XW0uUVQrQ&_nc_ad=z-m&_nc_cid=0&_nc_zt=23&_nc_ht=scontent-fra5-1.cdninstagram.com&_nc_gid=N2Y4t8KKxi1NhQHP6JJi7g&_nc_ss=7a22e&oh=00_Af5cnjJ0LLVjtsAOZ3nINGZOxfY7GXs4J1Iy_L5VMFhvvQ&oe=6A16339F",
    tags: ["Offgrid", "Mindfulness"],
  },
  {
    name: "Stone Techno Festival",
    slug: "stone-techno-festival",
    start: "2026-07-10",
    end: "2026-07-12",
    location: "Essen",
    country: "Germany",
    description: "Rigorously curated three-day techno festival at the UNESCO World Heritage Zeche Zollverein industrial complex in Essen.",
    img: "https://media.essen.de/media/emg_1/essen_tourismus/bilder_neu_1/veranstaltungen_9/stone_techno/StoneTechno-V3-Martijn-49.jpg",
    tags: ["Electronic", "Techno"],
  },
  {
    name: "Butik Festival",
    slug: "butik-festival",
    start: "2026-07-14",
    end: "2026-07-18",
    location: "Tolmin",
    country: "Slovenia",
    description: "Intimate boutique festival at the confluence of two alpine rivers in the Soča Valley, Slovenia, capped at 2,500 people.",
    img: "https://images.xceed.me/blog/wp-content/uploads/2025/07/08140915/Butik-Festivail-Slovenia-2025-guide-XCEED.jpg",
    tags: ["Electronic", "Techno", "Offgrid"],
  },
  {
    name: "The Festival of Creativity",
    slug: "the-festival-of-creativity",
    start: "2026-07-17",
    end: "2026-07-26",
    location: "Ticha-Dolní Dvořiště",
    country: "Czech Republic",
    description: "Intimate 125-person creative festival in Czech forest hills. All-inclusive week of workshops from dance to fire-making, nightly campfire singing.",
    img: "img/2021_09_satfestivalfirebannerstyle.jpg",
    tags: ["Arts", "Mindfulness", "Offgrid"],
  },
  {
    name: "WHOLE",
    slug: "whole",
    start: "2026-07-17",
    end: "2026-07-20",
    location: "Berlin",
    country: "Germany",
    description: "The world's largest queer electronic music festival, held in a former open-pit mine in Brandenburg, uniting music, politics, and liberation.",
    img: "https://www.ferropolis.de/images/slider/event.webp",
    tags: ["Electronic", "Techno"],
  },
  {
    name: "Dekmantel Festival",
    slug: "dekmantel-festival",
    start: "2026-07-29",
    end: "2026-08-02",
    location: "Amsterdam",
    country: "Netherlands",
    description: "Amsterdam's most revered electronic music festival, held in a forest, championing depth, curation, and community over spectacle.",
    img: "https://cdn.mos.cms.futurecdn.net/SSFvwqh73Jd3iV2cRJXPwa.jpg",
    tags: ["Electronic", "Techno"],
  },
  {
    name: "Traumburg Festival",
    slug: "traumburg-festival",
    start: "2026-07-30",
    end: "2026-08-02",
    location: "Schloss Dornburg",
    country: "Germany",
    description: "Small independent arts and music festival at an abandoned baroque castle in eastern Germany, built on radical collective equality and a Do It With Others ethos.",
    img: "https://groove.de/wp-content/uploads/2022/09/Traumburg-Festival_2022_Header_-by-Leon-Schuck.jpeg",
    tags: ["Electronic", "World Music", "Arts"],
  },
  {
    name: "Ezera Skaņas",
    slug: "ezera-skaas",
    start: "2026-07-31",
    end: "2026-08-02",
    location: "Vestiena",
    country: "Latvia",
    description: "Rare sunrise lake festival in Latvia where audiences row out onto the water before dawn to witness music greet the light.",
    img: "https://musiclatvia.lv/wp-content/uploads/2025/11/Ezera-skanas.jpg",
    tags: ["Electronic", "Arts", "Offgrid"],
  },
  {
    name: "Komorebi Festival",
    slug: "komorebi-festival",
    start: "2026-07-31",
    end: "2026-08-03",
    location: "Golden Lake",
    country: "Georgia",
    description: "Underground electronic music festival on Georgia's Black Sea coast, celebrating the harmony of sea, forest, music, and human connection.",
    img: "https://images.xceed.me/blog/wp-content/uploads/2025/03/26200317/316966312_676324157188312_2741729808736149085_n-e1743012233956.jpg",
    tags: ["Electronic", "Techno", "Offgrid", "Arts"],
  },
  // AUGUST (added)
  {
    name: "Mahagoni Festival",
    slug: "mahagoni-festival",
    start: "2026-08-06",
    end: "2026-08-09",
    location: "Rittergut Etzdorf",
    country: "Germany",
    description: "Four-day electronic music and arts festival at a historic Saxon estate, hosting over 80 acts across six stages in a communal, awareness-focused environment.",
    img: "https://bmg-images.forward-publishing.io/2025/07/24/66acb0c3-1df6-470e-bf2a-0574a3b5fde0.jpeg?rect=0%2C59%2C1247%2C652&w=1024&auto=format",
    tags: ["Electronic", "Techno", "Offgrid"],
  },
  {
    name: "ZMAR Festival",
    slug: "zmar-festival",
    start: "2026-08-07",
    end: "2026-08-09",
    location: "Zmar",
    country: "Portugal",
    description: "Three-day electronic music gathering at Zmar Eco Camp in the Alentejo cork oak forest, where solar-powered stages meet a natural lake and the unhurried pace of rural Portugal.",
    img: "https://scontent-fra3-1.xx.fbcdn.net/v/t39.30808-6/702962049_976668318444376_6866225458322428624_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=127cfc&_nc_ohc=1dyi3AD7ayEQ7kNvwHOC_GY&_nc_oc=AdpJ5JIiNrpbp6E9EsRlQenDNNqhfPSrIyrHE74RlNnAwvNwI5prt5-45QAv_SOUKpc&_nc_zt=23&_nc_ht=scontent-fra3-1.xx&_nc_gid=XdBURtiT37ho45itZ0Pefg&_nc_ss=7b2a8&oh=00_Af7qRXP3Tqcu3Zc84YkFXpjZbX9EaJsN0hX9db0Fig_Nkw&oe=6A15528A",
    tags: ["Electronic", "Techno", "Offgrid"],
  },
  {
    name: "Dimensions Festival",
    slug: "dimensions-festival",
    start: "2026-08-27",
    end: "2026-08-31",
    location: "Tisno",
    country: "Croatia",
    description: "Five-day underground electronic odyssey at The Garden Resort on Croatia's Adriatic coast — house, techno, electro, breaks and minimal with 150+ artists, boat parties and after-parties at Barbarella's.",
    img: "https://dimensionsfestival.com/wp-content/uploads/2024/10/BB240829_DIMENSIONS_2024_Analogue_JakeDavis_@jakephilipdavis_@khromacollective-865811180035.jpg",
    tags: ["Electronic", "Techno"],
  },
  // SEPTEMBER (added)
  {
    name: "Draaimolen Festival",
    slug: "draaimolen-festival",
    start: "2026-09-04",
    end: "2026-09-05",
    location: "Tilburg",
    country: "Netherlands",
    description: "100% independent non-profit electronic festival in the atmospheric forests of Tilburg, where world-class stage design meets raw Dutch woodland across six distinct sonic environments.",
    img: "https://media.eurotravelo.com/wp-content/uploads/2026/03/drymoo.webp",
    tags: ["Electronic", "Techno", "Offgrid"],
  },
  {
    name: "Plisskën Festival",
    slug: "plisskn-festival",
    start: "2026-09-12",
    end: "2026-09-13",
    location: "Athens",
    country: "Greece",
    description: "Two-day avant-garde music festival in Athens blending electronic, indie, hip-hop, punk and experimental sounds across multiple stages, with a commitment to bold curation, sustainability and community.",
    img: "https://viberate-upload.ams3.cdn.digitaloceanspaces.com/prod/entity/festival/plissken-festival-RbWEE",
    tags: ["Electronic", "Techno"],
  },
  {
    name: "Omana",
    slug: "omana",
    start: "2026-09-30",
    end: "2026-10-06",
    location: "Germany",
    country: "Germany",
    description: "Week-long outdoor festival in Germany by HomeAgain Berlin. Deep electronic music, art and community in nature as summer gives way to autumn.",
    img: "/img/Omana_2026.webp",
    tags: ["Electronic", "Offgrid"],
  },
  // OCTOBER–2027 (added)
  {
    name: "C2C Festival",
    slug: "c2c-festival",
    start: "2026-10-29",
    end: "2026-11-01",
    location: "Turin",
    country: "Italy",
    description: "Italy's largest indoor music festival in Turin, celebrating 25 years of avant-garde electronic, experimental and contemporary sound across four days each October.",
    img: "https://cdn.sanity.io/images/rizm0do5/production/6987a68c700a10aa9a163e321cc46403eff44aba-2048x1365.jpg",
    tags: ["Electronic", "Arts", "Techno"],
  },
  {
    name: "Horst Arts & Music",
    slug: "horst-arts--music",
    start: "2027-05-06",
    end: "2027-05-08",
    location: "Brussels",
    country: "Belgium",
    description: "Multidisciplinary electronic music and contemporary arts festival at a decommissioned military telecom arsenal near Brussels.",
    img: "https://cdn.prod.website-files.com/64edfd0797f6eba52008af10/6536d1ac5150e21dc0cbef67_2.%20Illias%20Teirlinck.webp",
    tags: ["Electronic", "Techno", "Arts"],
  },
  {
    name: "Flash Festival",
    slug: "flash-festival",
    start: "2027-05-19",
    end: "2027-05-22",
    location: "Castiglion Fiorentino",
    country: "Italy",
    description: "Boutique music and lifestyle festival in Tuscany combining soulful electronic music with wine, food, and genuine Italian culture on a working agriturismo estate.",
    img: "https://static.myeasol.net/rails/active_storage/representations/proxy/eyJfcmFpbHMiOnsiZGF0YSI6IjQzNzJiM2QzLTkzZDUtNGMxMC1iZDAwLTJkNWUzOGFkNDFkOCIsInB1ciI6ImJsb2JfaWQifX0=--e7da4129e788904080cab5f773eeca01c8c68c90/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJwbmciLCJyZXNpemVfdG9fbGltaXQiOlsxOTIwLG51bGxdLCJzYXZlciI6eyJzdHJpcCI6dHJ1ZSwicXVhbGl0eSI6ODV9fSwicHVyIjoidmFyaWF0aW9uIn19--e748e971f8cf7cad636cd59f6d8e5dff0b37c6cd/FF26WebsitePictures10.png",
    tags: ["Electronic", "Mindfulness"],
  },
];

export default FESTIVALS_META;
